### ISSUE TITLE
Interface Support Request: Network, QRCode, SecurityCardManagement, SigningBoxInput, UserInfo.

### ISSUE THREAD

**Issue by asnov** [Strafi/Free-TON-DeBot-Browser#1]
Great work!  
Please, add support of the following interfaces from [DeBot consortium](https://github.com/tonlabs/DeBot-IS-consortium):  
- [x] Network,  
- [x] QRCode,  
- [ ] SecurityCardManagement,  
- [x] SigningBoxInput,  
- [x] UserInfo.  

Thank you!

**Comment by Strafi** [comment]
UserInfo is supported in the latest release

**Comment by senitskiy** [comment]
ok. Please add string to "scripts" in package.json: "wasm":   "cp ./node_modules/@tonclient/lib-web/tonclient.wasm public".

**Comment by Strafi** [comment]
All resolved in v2, except SecurityCardManagement (will log for backlog)
