### ISSUE TITLE
build - work (with result), npm run serve - too work, but without rusult.

### ISSUE THREAD

**Issue by senitskiy** [Strafi/Free-TON-DeBot-Browser#2]
build from this repository work (with result), npm run serve - too work, but without rusult. What am I doing wrong? ERROR Console (533e08ba-f421-4a44-82b7-2b7154d10dbf:292 Uncaught (in promise) LinkError: WebAssembly.instantiate(): Import #1 module="wbg" function="__wbg_new0_8e8ab0e7714cf1dd" error: function import requires a callable)

**Comment by Strafi** [comment]
@senitskiy This issue is connected to tonclient js SDK. Try to download new binaries from here https://github.com/tonlabs/ton-client-js (links are at the bottom or README), and then replace public/tonclient.wasm with the new one.
